#!/usr/bin/env bash
# Fetches Bosch's BMI270 and BMM150 reference drivers into
# components/bosch_sensortec/, which is what compass.cpp needs to produce a
# heading while stationary.
#
# CMakeLists.txt calls this automatically on the first configure, the same way
# it clones sunset - so this exists for reverting, for re-fetching after a
# network failure, and for anyone who would rather run it by hand.
#
#   ./tools/fetch_bosch_drivers.sh            fetch
#   ./tools/fetch_bosch_drivers.sh --revert   remove, back to GNSS-course only
#   ./tools/fetch_bosch_drivers.sh --keep-build
#         fetch without deleting build/. CMakeLists.txt passes this, and must:
#         configure runs with build/ as the process working directory, so a
#         script that deletes it from underneath cmake takes cmake's own CWD
#         with it. The failure is "Current working directory cannot be
#         established" from component.cmake, followed by idf.py falling over
#         trying to read a log file out of the directory that just vanished -
#         neither of which names this script.
#
# WHY VENDOR THESE RATHER THAN DRIVE THE REGISTERS DIRECTLY
# The BMI270's auxiliary I2C master - which is the only way to reach the
# BMM150 - is not a bus you can drive by writing the obvious registers in the
# obvious order. Its write primitive needs AUX_WR_DATA set *before*
# AUX_WR_ADDR, because writing the address is what triggers the transaction;
# it has to poll the aux_busy bit between operations; and it has to drop
# advanced power save around each transfer. Several attempts at a hand-rolled
# version in the source project failed with aux_err on every transaction, and
# none of the failures pointed at the cause. M5's own driver wraps this same
# API.
#
# The BMI270's 8 KB configuration image ships inside bmi270.c, so fetching the
# driver gets the blob too - there is no separate config-file step.
#
# Both drivers are BSD-3-Clause, and are gitignored rather than committed:
# byte-exact fetches from a pinned upstream, under a different licence to this
# repo. Same reasoning as components/fatfs/.
#
# src: ported from tools/fetch_bosch_drivers.sh in
#      Sudrien/m5tab5_esp_idf_m135_examples.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="$HERE/components/bosch_sensortec"

BMI270_URL="https://raw.githubusercontent.com/boschsensortec/BMI270-Sensor-API/master"
BMM150_URL="https://raw.githubusercontent.com/boschsensortec/BMM150-Sensor-API/master"

BMI270_FILES="bmi2.c bmi2.h bmi2_defs.h bmi270.c bmi270.h"
BMM150_FILES="bmm150.c bmm150.h bmm150_defs.h"

KEEP_BUILD=0
if [ "${1:-}" = "--keep-build" ]; then
    KEEP_BUILD=1
    shift
fi

if [ "${1:-}" = "--revert" ]; then
    rm -rf "$DEST"
    # Same hazard in reverse: a --revert called from configure must not take
    # cmake's working directory with it.
    if [ "$KEEP_BUILD" = "0" ]; then rm -rf "$HERE/build"; fi
    echo "removed $DEST"
    echo "compass.cpp guards on __has_include, so the next build succeeds"
    echo "without it - the dial falls back to GNSS course over ground."
    exit 0
fi

mkdir -p "$DEST"

for f in $BMI270_FILES; do
    echo "fetching $f"
    curl -fsSL "$BMI270_URL/$f" -o "$DEST/$f"
done
for f in $BMM150_FILES; do
    echo "fetching $f"
    curl -fsSL "$BMM150_URL/$f" -o "$DEST/$f"
done

# Sanity check: bmi270.c carries the 8 KB config image, so a truncated or
# redirected download shows up here rather than as a sensor that silently
# fails to initialise three layers away.
if ! grep -q "bmi270_config_file" "$DEST/bmi270.c"; then
    echo "bmi270.c does not contain bmi270_config_file[] - bad download?" >&2
    rm -rf "$DEST"
    exit 1
fi

cat > "$DEST/CMakeLists.txt" <<'EOF'
# Generated by tools/fetch_bosch_drivers.sh. Not committed - see .gitignore.
idf_component_register(
    SRCS "bmi2.c" "bmi270.c" "bmm150.c"
    INCLUDE_DIRS "."
)
# Bosch's drivers are not warning-clean under IDF's default flags, and the
# warnings are all in vendored code nobody here should be editing.
target_compile_options(${COMPONENT_LIB} PRIVATE
                       -Wno-unused-but-set-variable -Wno-sign-compare)
EOF

# A stale build directory reuses old objects and leaves the sensor dead with
# perfectly good sources sitting right there. Skipped under --keep-build,
# where cmake is running inside that very directory - see the header.
if [ "$KEEP_BUILD" = "0" ]; then
    rm -rf "$HERE/build"
fi
echo
echo "vendored into components/bosch_sensortec; run idf.py build"
